version: 0.2

phases:
    pre_build:
        commands:
            - echo Install source NPM dependencies...
            - npm install
    build:
        commands:
            - echo Deployment started on `date`
            - echo Deploying with the Serverless Framework
            - node_modules/.bin/sls deploy -v -s $ENV_NAME
    post_build:
        commands:
            - echo Deployment completed on `date`
