---
swagger: "2.0"
info:
  version: "2020-12-03T07:25:41Z"
  title: "dev-back-ms-people"
host: "e7ic1k5rv5.execute-api.us-east-1.amazonaws.com"
basePath: "/dev"
schemes:
- "https"
paths:
  /v1/people/:
    get:
      parameters:
      - name: "id"
        in: "query"
        description: "ID creacion de personaje, consume el SWAPI."
        required: true
        type: "integer"
      responses: 
        "200":
          description: ""
    post:
      parameters:
      - name: "id"
        in: "query"
        description: "ID creacion de personaje, consume el SWAPI."
        required: true
        type: "integer"
      responses: 
        "200":
          description: ""
  /v1/people-saved:
    get:
      parameters:
      - name: "id"
        in: "query"
        description: "ID creacion de personaje, consume el SWAPI."
        required: true
        type: "integer"
      responses: 
        "200":
          description: ""
